---
apiVersion: v2
name: script-exporter
description:
  Prometheus exporter to execute scripts and collect metrics from the output or
  the exit status.
type: application
version: 3.1.0
appVersion: v3.0.1
